-- crie uma view com o nome  produtos_integracao_pda

SELECT
p.CODITEM,
p.CODBARRA,
p.DESCRICAO,
p.ABREVIA,
p.OBSERVACOES,
-- p.FOTO_PRODUTO1,
p.GRUPO,
g.NOMEGRUPO,
p.CATEGORIA,
c.DESCRICAO AS NOMECATEGORIA,
p.FAMILIA, 
f.DESCRICAO NOMEFAMILIA,
p.UNIDADE,
p.CUSTO,
e.UNITARIO,
case
	when e.PROMOCAO = '0,0' then e.UNITARIO
	ELSE e.PROMOCAO
END AS PROMOCAO,
case
	when e.UNITARIOATACADO = '0,0' then e.UNITARIO
	ELSE e.UNITARIOATACADO
END AS UNITARIOATACADO,
case
	when (e.PRECOREVENDA = '0,0' OR e.PRECOREVENDA = '' OR e.PRECOREVENDA IS NULL OR e.PRECOREVENDA = NULL) then e.UNITARIO
	ELSE e.PRECOREVENDA
END AS PRECOREVENDA,
e.ALIQUOTASAIDA,
p.CFOPVENDAECF
FROM estoques e 
JOIN produto p
ON e.ID_PRODUTO = p.CODITEM
JOIN categorias c 
ON p.CATEGORIA = c.ID_CATEGORIA
JOIN grupo g
on p.GRUPO = g.CODGRUPO
JOIN familias f 
ON p.FAMILIA = f.CODIGO
WHERE e.ID_EMPRESA = 1
AND p.ATIVO = 'S'
AND p.USOCONSUMO = 'N' 
AND e.ENVIA_PDA = 'S' 