<?php
session_start();

require_once '../conexao.php';
// variaveis recuperadas via post
$userid = $_POST['userid'];
$id_empresa = $_POST['id_empresa'];
$tipopedido = $_POST['tipopedido'];
$vendedor = $_POST['vendedor'];
$planopgto = $_POST['planopgto'];
$planoconta = $_POST['planoconta'];
$id_banco = $_POST['id_banco'];
$id_pedido_cliente = $_POST['id_pedido'];
$observacao = $_POST['observacao'];
// $userid = 1;
// $id_empresa = 1;
// $tipopedido = 10;
// $vendedor = 1;
// $planopgto = 1;
// $planoconta = 1;
// $id_banco = 1;
// $id_pedido_cliente = 22;
// $observacao = "teste";
// recupera o ultimo id da sequenciador do sia prevenda
$sql2 = "SELECT * FROM sys_sequenciador s WHERE s.TABELA = 'PREVENDA'";
$sql2 = $conexao->prepare($sql2);
$sql2->execute();
$prevenda_id = $sql2->fetchAll(PDO::FETCH_ASSOC);

$id_venda = $prevenda_id[0]['VALOR'] + 1;

// recupera os dados do cliente
$sql3 = "SELECT * FROM clientes c WHERE c.CODIGOCLI =:idcliente ";
$sql3 = $conexao->prepare($sql3);
$sql3->bindValue(':idcliente',$userid);
$sql3->execute();
$cliente = $sql3->fetchAll(PDO::FETCH_ASSOC);
// print_r($cliente[0]);

// apos os dados recuperados, hora de percistir os dados do carrinho para setar como finalizado e colocar o valor final dos itens
$sql5 = "
SELECT SUM(ic.TOTAL) as total FROM carrinho_ecommerce c 
JOIN itens_carrinho_ecommerce ic
ON c.ID = ic.ID_CARRINHO_ECOMMERCE WHERE c.ID_CLIENTE =:idcliente AND c.`STATUS` = 'A' AND c.ID =:id_pedido_cliente";
$sql5 = $conexao->prepare($sql5);
$sql5->bindValue(':id_pedido_cliente',$id_pedido_cliente);
$sql5->bindValue(':idcliente',$userid);
$sql5->execute();
$total_produtos_carrinho = $sql5->fetchAll(PDO::FETCH_ASSOC);
// print_r($total_produtos_carrinho[0]['total']);

// insere o valor final do carrinho na tabela
$sql6 = "UPDATE carrinho_ecommerce c SET c.TOTAL = :total WHERE c.ID =:id_pedido";
$sql6 = $conexao->prepare($sql6);
$sql6->bindValue(':total',$total_produtos_carrinho[0]['total']);
$sql6->bindValue(':id_pedido',$id_pedido_cliente);
$sql6->execute();

$sql7 = "SELECT * FROM carrinho_ecommerce c WHERE c.ID =:id";
$sql7 = $conexao->prepare($sql7);
$sql7->bindValue(':id',$id_pedido_cliente);
$sql7->execute();
$carrinho = $sql7->fetchAll(PDO::FETCH_ASSOC);
// print_r($carrinho[0]['TOTAL']);




// -- INSERT prevenda
$sql4 = "INSERT INTO `prevenda` (
`EMPRESA`,
 `VENDA`, 
 `TIPOVENDA`, 
 `CODIGOCLI`, 
 `NOMECLI`, 
 `ENDERCLI`, 
 `BAIRROCLI`, 
 `CIDADECLI`, 
 `ESTADOCLI`, 
 `CEPCLI`, 
 `FONECLI`, 
 `VLR_DESCONTO`, 
 `VLRTOTAL`, 
 `CPFCGC`, 
 `IDENINSC`, 
 `APROVADO`, 
 `DATAAPROV`, 
 `TIPOAPROV`, 
 `SITUACAO`, 
 `EMISSAO`, 
 `OBSERVACAO`, 
 `FORMAPAGTO`, 
 `ID_VENDEDOR`, 
 `STATUS`, 
 `ID_PLANOPGTO`, 
 `ID_FORMAPGTO`, 
 `ID_TIPOPEDIDO`, 
 `CANCELADO`, 
 `ENTRADA`, 
 `VALOR_ENTRADA`, 
 `ENTRADA_PAGA`, 
 `DATA_ENTRADA`, 
 `OUTRO_DESC`, 
 `OUTRO_DESC_ORIGINAL`, 
 `ACRESCIMO`, 
 `ACRESCIMO_ORIGINAL`, 
 `ID_PREVENDA`, 
 `ID_DAV`, 
 `CAIXA`, 
 `CUPOM`, 
 `STATUSPAF`, 
 `SELECIONADO`, 
 `ID_DAVSTR`, 
 `ID_PREVENDASTR`, 
 `NOTA`, 
 `SERIE`, 
 `NOTAIMPRESSA`, 
 `BASEDECALCULO`, 
 `VALORICMS`, 
 `BASEST`, 
 `VALORICMSST`, 
 `TOTALSERVICOS`, 
 `VALORFRETE`, 
 `VALORSEGURO`, 
 `VALORDESPESAS`, 
 `VALORIPI`, 
 `ID_TRANSPORTADOR`, 
 `PLACA`, 
 `FRETEPORCONTA`, 
 `QUANTIDADE`, 
 `ESPECIE`, 
 `MARCA`, 
 `PESOBRUTO`, 
 `PESOLIQUIDO`, 
 `VALORISS`, 
 `ALIQUOTAISS`, 
 `BASEISS`, 
 `CARIMBO`, 
 `INFOADICIONAL`, 
 `FATURAMENTOIMPRESSO`, 
 `DATAENTREGA`, 
 `DATAGERACAONF`, 
 `ID_AUTORIZADO`, 
 `ID_USUARIOCADASTRO`, 
 `DEVOLVIDO`, 
 `DATADEVOLUCAO`, 
 `NFDEVOLUCAO`, 
 `SERIEDEVOLUCAO`, 
 `ENTREGAR`, 
 `LOCALENTREGADIF`, 
 `ENDERECOENTREGA`, 
 `BAIRROENTREGA`, 
 `CIDADEENTREGA`, 
 `ESTADOENTREGA`, 
 `CEPENTREGA`, 
 `TELEFONEENTREGA`, 
 `CONTATOENTREGA`, 
 `CCF`, 
 `ID_PEDIDOPALM`, 
 `DATA_VISITA`, 
 `ENTREGUE`, 
 `DTRECEBIMENTOENTREGA`, 
 `HORARECEBIMENTOENTREGA`, 
 `OBSERVACAO_ENTREGA`, 
 `ID_VENDEDOR_EXTERNO`, 
 `RETIRADOPOR`, 
 `HORA`, 
 `MD5`, 
 `BASEPIS`, 
 `VL_PIS`, 
 `BASECOFINS`, 
 `VL_COFINS`, 
 `IMPRESSO`, 
 `PARTICIPAPISCOFINS`, 
 `IDROMANEIO`, 
 `UF`, 
 `VL_PIS_ST`, 
 `VL_COFINS_ST`, 
 `RECEBIDO`, 
 `DTRECEBIMENTO`, 
 `RECEBIMENTOOK`, 
 `ID_PEDIDOCOMPRA`, 
 `VALIDADE_ORCAMENTO`, 
 `ID_PROFISSIONAL`, 
 `ID_ROTA`, 
 `LIBERADO`, 
 `USUARIO_LIBERACAO`, 
 `DATA_LIBERACAO`, 
 `FRETE`, 
 `USUARIOGERENCIA`, 
 `LIBERADOGERENCIA`, 
 `DATALIBERACAOGERENCIA`, 
 `SIMPLES_REMESSA`, 
 `ID_ADM`, 
 `EDITADOGERENCIA`, 
 `SALDODC`, 
 `STATUS_CAIXA_OPERADOR`, 
 `SOLUCAO_PENDENCIA`, 
 `ID_USUARIO_CAIXA_OPERADOR`, 
 `SELECAO`, 
 `CORPORATIVO`, 
 `ID_CARIMBO_OBS`, 
 `ID_CARIMBO_ADICIONAIS`, 
 `ID_CARIMBO`, 
 `DATA_TRANSACAO`, 
 `ID_FORMAPGTO_ENTRADA`, 
 `ID_ADM_ENTRADA`, 
 `NUMDOC_ENTRADA`, 
 `NUM_PARCELAS_ENTRADA`, 
 `TIPO_ENTRADA`, 
 `ID_PLANOCONTA`, 
 `VFCP_TOT`, 
 `VFCPUFDEST_TOT`, 
 `VICMSUFDEST_TOT`, 
 `VICMSUFREMET_TOT`, 
 `VFCPST_TOT`, 
 `VFCPSTRET_TOT`, 
 `ID_MEIO_PGTO_CAB`, 
 `INDICADOR_PRESENCA`, 
 `IDDEST`, 
 `BASE_IPI`, 
 `CONSUMO_FINAL`, 
 `DESTINO_DEMONSTRACAO`, 
 `ACRESCIMO_PROMOCIONAL_PL_PGTO`, 
 `ACRESCIMO_PL_PGTO`, 
 `VICMSDESON_TOT`, 
 `INCIDE_IPI_BC_ICMS`, 
 `DESCONTAR_DESONERADO`, 
 `ID_USUARIO_EDICAO`, 
 `NFCE`, 
 `PLANO_ALTERADO`, 
 `TEXTO_COMP_OBS`, 
 `STATUS_APROVACAO`, 
 `GPS_LONGITUDE`, 
 `GPS_LATITUDE`, 
 `ADM_ECOMMERCE`, 
 `PARCELAS_ECOMMERCE`, 
 `PEDIDO_EXPOSICAO`, 
 `DESPESAS_BOLETO`, 
 `ID_INTERMEDIADOR`, 
 `VLR_ENTREGA_ECOMMERCE`, 
 `VLR_MEIO_PGTO_ECOMMERCE`, 
 `VLR_COMISSAO_ECOMMERCE`, 
 `ID_PEDIDO_ORIGEM`, 
 `ID_PEDIDO_ECOMMERCE`, 
 `TIPO_ECOMMERCE`, 
 `ID_VENDA_PDV_ECOMMERCE`, 
 `ORCAMENTO_PDV`, 
 `VALORCONTRATO`, 
 `ID_CONFERENCIA`
 ) VALUES (
 {$id_empresa}, 
 {$id_venda}, 
 '', 
 {$cliente[0]['CODIGOCLI']}, 
 '{$cliente[0]['NOMECLI']}', 
 '{$cliente[0]['ENDERCLI']}', 
 '{$cliente[0]['BAIRROCLI']}', 
 '{$cliente[0]['CIDADECLI']}', 
 '{$cliente[0]['ESTADOCLI']}', 
 '{$cliente[0]['CEPCLI']}', 
 '{$cliente[0]['FONECLI']}', 
 0.00, 
 '{$carrinho[0]['TOTAL']}', 
 '{$cliente[0]['CPFCGC']}', 
 '{$cliente[0]['IDENINSC']}', 
 'N', 
 NULL, 
 '', 
 'N', 
 current_date(), 
 '{$observacao}', 
 NULL, 
 '{$vendedor}', 
 '1', 
 '{$planopgto}', 
 '{$carrinho[0]['FORMAPGTO']}', 
 '{$tipopedido}', 
 'N', 
 'N', 
 0.00, 
 'N', 
 NULL, 
 0.00, 
 0.00, 
 0.00, 
 0.00, 
 0, 
 0, 
 0, 
 0, 
 'N', 
 NULL, 
 NULL, 
 NULL, 
 0, 
 NULL, 
 'N', 
 0.00, 
 0.00, 
 0.00, 
 0.00, 
 0.00, 
 0.00, 
 0.00, 
 0.00, 
 0.00, 
 NULL, 
 NULL, 
 9, 
 1.000, 
 'VOLUMES', 
 NULL, 
 0.000, 
 0.000, 
 0.00, 
 0.00, 
 0.000, 
 NULL, 
 NULL, 
 'N', 
 current_date(), 
 NULL, 
 NULL, 
 1000000, 
 'N', 
 NULL, 
 NULL, 
 NULL, 
 'S', 
 'N', 
 '{$cliente[0]['ENDERCLI']}', 
 '{$cliente[0]['BAIRROCLI']}', 
 '{$cliente[0]['CIDADECLI']}', 
 '{$cliente[0]['ESTADOCLI']}', 
 '{$cliente[0]['CEPCLI']}', 
 '{$cliente[0]['FONECLI']}', 
 NULL, 
 NULL, 
 NULL, 
 NULL, 
 'N', 
 NULL, 
 NULL,
 NULL, 
 NULL, 
 'O PROPRIO', 
 current_time(), 
 NULL, 
 0.00, 
 0.00, 
 0.00, 
 0.00, 
 'N', 
 'S', 
 NULL, 
 NULL, 
 0.00, 
 0.00, 
 'N', 
 NULL, 
 'N', 
 NULL, 
 current_date(), 
 1, 
 0, 
 'N', 
 NULL, 
 NULL, 
 0.00, 
 NULL, 
 'N', 
 NULL, 
 'N', 
 NULL, 
 'N', 
 0.00, 
 'X', 
 NULL, 
 NULL, 
 'N', 
 'N', 
 NULL, 
 NULL, 
 NULL, 
 NULL, 
 NULL, 
 NULL, 
 NULL, 
 NULL, 
 NULL, 
 '{$planoconta}', 
 0.00, 
 0.00, 
 0.00,
 0.00, 
 0.00, 
 0.00, 
 NULL, 
 1, 
 NULL, 
 0.00, 
 'N', 
 NULL, 
 0.000, 
 0.000, 
 0.00, 
 'N', 
 'N', 
 1000000, 
 0, 
 'N', 
 NULL, 
 1, 
 NULL, 
 NULL, 
 NULL, 
 0, 
 'N', 
 0.00, 
 NULL, 
 NULL, 
 NULL, 
 NULL, 
 0, 
 '0', 
 0, 
 0, 
 'N', 
 0.00, 
 0
 )";
$sql4 = $conexao->prepare($sql4);
$sql4->execute();


// recupera dados dos itens do carrinho 
$sql8 = "SELECT * FROM itens_carrinho_ecommerce c WHERE c.ID_CARRINHO_ECOMMERCE =:id_pedido";
$sql8 = $conexao->prepare($sql8);
$sql8->bindValue(':id_pedido',$id_pedido_cliente);
$sql8->execute();
$itens_carrinho = $sql8->fetchAll(PDO::FETCH_ASSOC);
// print_r($itens_carrinho);
foreach($itens_carrinho as $itens_carrinho){
    $sql5 =
    "INSERT INTO `produtos_prevenda` (
    `EMPRESA`, 
    `VENDA`, 
    `CODIGO`, 
    `DESCRICAO`, 
    `UNIDADE`, 
    `QTDE`, 
    `UNITARIO`, 
    `ALIQUOTA`, 
    `CUSTO`, 
    `ID_PRODUTO`, 
    `TOT_ITEM`, 
    `DESCONTO`, 
    `TOTALDESCONTO`, 
    `DESC_RATEIO`, 
    `ENCARGO_RATEIO`, 
    `PRECOVENDA`, 
    `PESOLIQUIDO`, 
    `PESOBRUTO`, 
    `COMISSAO`, 
    `INFOADICIONAL`, 
    `DADOADICIONAL`, 
    `CFOP`, 
    `BASEDECALCULO`, 
    `ALIQUOTAICMS`, 
    `VALORICMS`, 
    `CST`, 
    `FATURADO`, 
    `VALORIPI`, 
    `DIFEUNITARIOVENDA`, 
    `IMPOSTO`, 
    `CONFERIDO`, 
    `TOTALBRUTO`, 
    `DEVOLVIDO`, 
    `CUSTOREAL`, 
    `CUSTOOPERACIONAL`, 
    `PRECO_CONCORRENTE`, 
    `MD5`, 
    `CANCELADO`, 
    `BASEPIS`, 
    `ALIQUOTAPIS`, 
    `VL_PIS`, 
    `BASECOFINS`, 
    `ALIQUOTACOFINS`, 
    `VL_COFINS`, 
    `ALIQ_ECF`, 
    `ID_DAV`, 
    `NUMERO_ITEM`, 
    `EMISSAO`, 
    `CST_PIS`, 
    `CST_COFINS`, 
    `SIT_TRIBUTARIA`, 
    `QTD_DEVOLVIDA`, 
    `MARKUP`, 
    `PRECOINICIAL`, 
    `SALDO_PRODUTO`, 
    `ID_TONALIDADE`, 
    `PRODUTO_PROMOCAO`, 
    `FRETE_RATEIO`, 
    `ACRESCIMO`, 
    `EDITADOGERENCIA`, 
    `UNITARIOBASE`, 
    `CSOSN`, 
    `ORIGEM_PRODUTO`, 
    `PROTOCOLO_ENTRE_ESTADOS`, 
    `VBCFCPUFDEST`, 
    `VBCUFDEST`, 
    `PFCPUFDEST`, 
    `PICMSUFDEST`, 
    `PICMSINTER`, 
    `PICMSINTERPART`, 
    `VFCPUFDEST`, 
    `VICMSUFDEST`, 
    `VICMSUFREMET`, 
    `VBCFCPST`, 
    `PFCPST`, 
    `VFCPST`, 
    `VBCFCPSTRET`, 
    `PFCPSTRET`, 
    `VFCPSTRET`, 
    `VFCP`, 
    `PFCP`, 
    `VBCFCP`, 
    `REDUCAO`, 
    `BASESUBSTITUICAO`, 
    `ICMSST`, 
    `REDUCAOST`,
    `MVA`, 
    `ALIQUOTAINTERNA_DEST`, 
    `vBCSTRet`, 
    `vICMSSTRet`, 
    `pST`, 
    `pCREDSN`, 
    `vCREDICMSSN`, 
    `BASE_IPI`, 
    `ALIQUOTA_IPI`, 
    `CST_IPI`, 
    `ID_ALIQUOTA`, 
    `UTRIB`, 
    `QTRIB`, 
    `VUNTRIB`, 
    `DISPENSAESTORNOCREDITO`, 
    `ACRESCIMO_PROMOCIONAL_PL_PGTO`, 
    `ACRESCIMO_PL_PGTO`, 
    `VICMSDESON`, 
    `MOTDESICMS`, 
    `COD_BENEFICIO`, 
    `ICMSSUBSTITUTO`, 
    `PEDIDOCLIENTE`, 
    `ITEMPEDIDOCLIENTE`, 
    `ID_PEDIDO_ECOMMERCE`, 
    `DESPESAS_BOLETO`, 
    `QTD_ENTREGUE`, 
    `ID_TINTOMETRIA`, 
    `FORMULA_TINTOMETRIA`, 
    `ID_PRODUCAO`, 
    `ID_PLANOCONTA_ITEM`
    ) VALUES (
    {$id_empresa}, 
    {$id_venda}, 
    '{$itens_carrinho['CODBARRA']}', 
    '{$itens_carrinho['DESCRICAO']}', 
    '{$itens_carrinho['UNIDADE']}', 
    '{$itens_carrinho['QTDE']}', 
    '{$itens_carrinho['UNITARIO']}', 
    '{$itens_carrinho['ALIQUOTA']}', 
    '{$itens_carrinho['CUSTO']}', 
    '{$itens_carrinho['ID_PRODUTO']}', 
    '{$itens_carrinho['TOTAL']}', 
    0.00, 
    0.00, 
    0.00, 
    0.00, 
    '{$itens_carrinho['UNITARIO']}', 
    0.000, 
    0.000, 
    0.000, 
    NULL, 
    NULL, 
    NULL, 
    0.00, 
    0.00, 
    0.00, 
    NULL, 
    'S', 
    0.00, 
    0.00, 
    0.00, 
    'N', 
    '{$itens_carrinho['TOTAL']}', 
    'N', 
    0.323, 
    0.323, 
    0.00,
     NULL, 
     'N', 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     2, 
     0, 
     1, 
     current_date(), 
     NULL,
     NULL, 
     NULL, 
     0.000, 
     2995.98, 
     '{$itens_carrinho['UNITARIO']}', 
     0.000, 
     NULL, 
     'N', 
     0.00, 
     0.00, 
     'N', 
     '{$itens_carrinho['UNITARIO']}', 
     NULL, 
     NULL, 
     NULL, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00, 
     0.00,
     0.00, 
     0.00, 
     0, 
     '{$itens_carrinho['ALIQUOTA']}', 
     NULL, 
     0.0000, 
     0, 
     'N', 
     0.000, 
     0.000, 
     0.00, 
     0, 
     NULL, 
     0.00, 
     NULL, 
     NULL, 
     NULL, 
     0.00, 
     0.000,
     NULL,
     NULL, 
     0, 
     NULL
     );
    ";
    $sql5 = $conexao->prepare($sql5);
    $sql5->execute();
}

$sql10 = "UPDATE sys_sequenciador s
SET s.VALOR = :id_venda
WHERE s.TABELA IN ('PREVENDA','PRODUTOS_PREVENDA')";
$sql10 = $conexao->prepare($sql10);
$sql10->bindValue(':id_venda',$id_venda);
$sql10->execute();

$sql11 = "UPDATE carrinho_ecommerce c SET
c.`STATUS` = 'F' WHERE c.ID =:id_pedido_cliente";
$sql11 = $conexao->prepare($sql11);
$sql11->bindValue(':id_pedido_cliente',$id_pedido_cliente);
$sql11->execute();

// Definir uma mensagem na resposta
$_SESSION['pedido_finalizado'] = true;

